### PR TITLE
Fix transpiling minified shader

### LINKED ISSUE #1481: Transpilation Issue With Viv Shaders
From #1475 there is handling of custom `out` for glsl 300.  Our shaders from https://github.com/hms-dbmi/viv are having an unneeded `out vec4 fragmentColor;` added even though we have `out vec4 color;` in them.  I seem to have boiled it down.

#### Actual Result
```error
luma.gl: GLSL compilation errors in fragment shader xr-layer-fragment-shader-1
150: precision highp float;precision highp int;precision highp SAMPLER_TYPE;
151: #define GLSLIFY 1
152: uniform SAMPLER_TYPE channel0;uniform SAMPLER_TYPE channel1;uniform SAMPLER_TYPE channel2;uniform SAMPLER_TYPE channel3;uniform SAMPLER_TYPE channel4;uniform SAMPLER_TYPE channel5;uniform vec2 sliderValues[6];uniform vec3 colorValues[6];uniform float opacity;uniform float majorLensAxis;uniform float minorLensAxis;uniform vec2 lensCenter;uniform bool isLensOn;uniform int lensSelection;uniform vec3 lensBorderColor;uniform float lensBorderRadius;uniform vec3 transparentColor;uniform bool useTransparentColor;in vec2 vTexCoord;out vec4 color;out vec4 fragmentColor;
^^^ ERROR: 'fragmentColor' : must explicitly specify all locations when using multiple fragment outputs
```
#### Expected Result
No extra `out` is added.
#### Reproduce Steps
Check out Viv and bump all dependencies including deck.gl (see [this branch](https://github.com/hms-dbmi/viv/tree/ilan-gold/deck.gl_beta8.5)).  Then set up the environment as per the instructions and run `npm start`, looking at the browser console.

Here's the problematic line:

https://github.com/hms-dbmi/viv/blob/ea3a16a2a467e093d9baa3fa583bdb379b3484b0/src/layers/XRLayer/xr-layer-fragment.webgl2.glsl#L41

I've also narrowed it down to what appear to be one specific issue after getting the raw bytes of the string:

```javascript
const replacement = /^[ \t]*out[ \t]+vec4[ \t]+(\w+)[ \t]*;\s+/m
const stringToBytes = ( str ) => {
  var ch, st, re = [];
  for (var i = 0; i < str.length; i++ ) {
    ch = str.charCodeAt(i);  // get char 
    st = [];                 // set up "stack"
    do {
      st.push( ch & 0xFF );  // push byte to stack
      ch = ch >> 8;          // shift value down by 1 byte
    }  
    while ( ch );
    // add stack contents to result
    // done because chars have "wrong" endianness
    re = re.concat( st.reverse() );
  }
  // return an array of bytes
  return re;
}
String.fromCharCode(111, 117, 116, 32, 118, 101, 99, 52, 32, 99, 111, 108, 111, 114, 59) // "out vec4 color;"
String.fromCharCode(111, 117, 116, 32, 118, 101, 99, 52, 32, 99, 111, 108, 111, 114, 59).match(replacement) // null
```

If this is just some sort of ascii issue I'm missing let me know!  I can be very careless sometimes!
#### To Do List 
  - [ ] Add label and assign to milestone
  - [ ] Coding
  - [ ] Test

#### To Do List 
  - [ ] Add label and assign to milestone 
  - [ ] Coding
  - [ ] Doc update
  - [ ] Whats new update 
  - [ ] Test

### PR DESCRIPTION
**Pull request by zakjan**
Fixes #1481

Changes:
- multiline regexes `/^[ \t]*…/m` replaced with `/\b…/`, to match on word boundaries on a single line in a minified shader
- ES100 replacement `in[ \t]+` -> `varying ` replaced with `in[ \t]+(.+;)` -> `varying $1`, to match shader varyings only, skip function arguments

### CODE REVIEW

**Comment by Pessimistress** [comment]
Add a test case that is minified?

**Comment by zakjan** [comment]
Added. There was one more change necessary, prevent `(.+;)` matching across multiple variables. I used `([^,;\)\]]+;)`. Is it good enough?

File: modules/shadertools/test/lib/transpile-shader-compress.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
+// copied from rollup-plugin-glslify
+export function compressShader(code) {
```
Comment (ibgreen) [inline modules/shadertools/test/lib/transpile-shader-compress.js:2]: Nits:
- `minifyShader`?
- Consistent names between main export and file name: `minify-shader.js`?
- I find it helpful to declare regexps as named well-named constants. This makes the code more self-documenting, it is quite hard to understand what a long regexp is intendeded to do.
- This could potentially be added as an export to the shadertools package (if so it needs a test case).

**Review by ibgreen — APPROVED** [review]
Thanks @zakjan !

**Comment by ibgreen** [comment]
@ilangold

**Comment by Pessimistress** [comment]
> `([^,;\)\]]+;)`

What about `[ \w]+;`

File: modules/shadertools/test/lib/transpile-shader-compress.js (hunk 1 above)
Comment (zakjan) [reply modules/shadertools/test/lib/transpile-shader-compress.js]: 1, 2 - updated
3 - right, this could be part of a larger overhaul
4- agree, when it's needed

**Comment by zakjan** [comment]
Right, changed to `[ \t\w]+;`

**Review by Pessimistress — APPROVED** [review]
